import React, { Component } from "react";
import { Link } from "react-router-dom";
import cthulu from "../images/ctu.jpg"
import "./index.css";
class Cthulu extends Component{
    render(){
        return(
            <div id= "body">
               <img src={cthulu} className="logo" alt="logo" />
                <p id= "text">O HORROR NA ARGILA

A coisa mais misericordiosa do mundo, creio eu, é a incapacidade da mente humana em correlacionar todo o seu conteúdo. Vivemos numa plácida ilha de ignorância em meio a negros mares de infinito, e não está escrito pela Providência que devemos viajar longe. As ciências, cada uma progredindo em sua própria direção, têm até agora nos causado pouco dano; mas um dia a junção do conhecimento dissociado abrirá visões tão terríveis da realidade e de nossa apavorante situação nela, que provavelmente ficaremos loucos por causa dessa revelação ou fugiremos dessa luz mortal rumo à paz e à segurança de uma nova Idade das Trevas.

Os teosofistas fizeram conjecturas sobre a apavorante imensidão do ciclo cósmico, do qual nosso mundo e a raça humana constituem meros incidentes transitórios. Eles aludiram a estranhas sobrevivências em termos que congelariam o nosso sangue se não fossem mascarados por ameno otimismo. Mas! não foi deles que veio o vislumbre das eras proibidas que me arrepiam quando nelas penso e me enlouquecem quando com elas sonho; esse vislumbre, como todos os pavorosos vislumbres da verdade, cintilou quando juntei duas peças separadas no caso, uma velha notícia de jornal e as anotações de um professor já falecido. Espero que ninguém mais venha a fazer essa junção; com certeza, se eu viver, nunca fornecerei voluntariamente elo algum de tão nefasta cadeia. Acho que o professor também pretendia guardar segredo sobre a parte que ele conhecia, e que teria destruído suas anotações se a morte súbita não o tivesse levado antes.

Meu conhecimento da coisa começou no inverno de 1926 a 1927 com a morte do meu tio-avô, George Gamell Angell, professor emérito de línguas semíticas da Universidade Brown, em Providence, Rhode Island. O professor Angell gozava de grande renome como autoridade em inscrições antigas e a ele recorriam com freqüência diretores de importantes museus, de modo que seu falecimento, aos noventa e dois anos de idade, deve ser lembrado por muitos. A nível local, esse interesse foi intensificado pela obscuridade da causa mortes. O professor retornava do navio de Newport quando caiu de repente, segundo testemunhas, após ter sido empurrado por um negro com jeito de marinheiro, saído de um dos suspeitos e escuros pátios na encosta íngreme que formava um atalho entre o cais e a casa do finado na rua Williams. Os médicos foram incapazes de achar qualquer distúrbio visível, mas concluíram, após perplexa discussão, que alguma obscura lesão cardíaca, agravada pela subida brusca de tão íngreme colina por tão idoso homem, fora responsável pelo óbito. Naquela época não vi motivo algum para discordar desse diagnóstico, mas ultimamente sinto-me inclinado a questionar e mais do que questionar.

Como herdeiro e executor do meu tio-avô, que morrera viúvo e sem filhos, esperava-se que eu examinasse seus papéis cuidadosamente, e com esse propósito levei todos os seus arquivos e caixas para minha residência em Boston. Grande parte do material que organizei será publicado mais tarde pela Sociedade Arqueológica Americana, mas havia uma caixa que eu achei extremamente enigmática e que me senti um tanto avesso a mostrá-la a outros olhos. Havia sido fechada com cadeado e não encontrei a chave até que me ocorreu examinar o chaveiro pessoal que o professor levava sempre no bolso. Consegui, de fato, abri-la, mas então pareceu-me que foi só para dar de cara com outro segredo ainda maior e mais impermeável. Pois qual poderia ser o significado do estranho baixo-relevo de argila e das esparsas anotações, comentários e recortes que achei? Teria o meu tio, nos últimos anos de vida, se tornado crédulo das mais superficiais imposturas? Resolvi que procuraria o excêntrico escultor responsável por essa aparente perturbação da paz de espírito de um velho.

O baixo-relevo era um tosco retângulo com menos de dois dedos de espessura e uns doze a quinze centímetros de comprimento, obviamente de origem moderna. O seu desenho, contudo, nada tinha de moderno na atmosfera e no que sugeria; pois, embora os caprichos do cubismo e do futurismo sejam muitos e desvairados, não reproduzem com freqüência aquela regularidade críptica que se insinua na escrita pré-histórica. E a maior parte daqueles desenhos com certeza parecia algum tipo de escrita, ainda que a minha memória, bastante familiarizada com os papéis e coleções do meu tio, não conseguisse identificá-la ou sequer suspeitar de suas afiliações mais remotas.

Acima desses hieróglifos aparentes havia uma figura de evidente intenção pictórica, embora sua execução impressionista impedisse uma idéia muito clara de sua natureza. Parecia um tipo de monstro, ou de símbolo representando um monstro, cuja forma só uma mente doentia poderia conceber. Se eu disser que minha algo extravagante imaginação lhe atribuía ao mesmo tempo os traços de um polvo, de um dragão e de uma caricatura humana, não estarei sendo infiel ao espírito da coisa. Uma cabeça polpuda e tentaculada encimava um corpo grotesco e escamoso dotado de asas rudimentares; mas era o contorno geral do todo que chocava. Atrás da figura havia uma vaga sugestão de cenário de arquitetura ciclópica.

Essa singularidade era acompanhada, além de uma pilha de recortes de jornal, por escritos com a caligrafia mais recente do professor Angell, sem qualquer pretensão a estilo literário. O que parecia ser o documento principal tinha por título “CULTO DE CTHULHU” em letras de fôrma, para evitar a leitura incorreta de palavra tão inaudita. Esse manuscrito estava dividido em duas seções, a primeira das quais intitulada “1925 -Sonho e Interpretação do Sonho de H. A. Wilcox, Rua Thomas, 7, Providence, R. L”, e a segunda, “Narrativa do Inspetor John R. Lagrasse, Rua Bienville, 121, Nova Orleans, La., na reunião de 1908 da S. A. A. – Notas do Mesmo, & Relato do Prof. Webb”. Todos os demais manuscritos eram notas breves, sendo algumas delas relatos de sonhos esquisitos de diferentes pessoas, citações de livros e revistas teosóficas (principalmente de A Atlântlda e a Perdida Lemúria de W. Scott-Elliott) ou ainda comentários sobre antiquíssimos e ainda remanescentes sociedades secretas e cultos proibidos,  com referências a trechos de compêndios de mitologia e antropologia tais como O Ramo de Ouro, de James G. Frazer, e Culto às Bruxas na Europa Ocidental, de Miss Murray. Os recortes referiam-se basicamente a doenças mentais raras e surtos de alucinações coletivas na primavera de 1925.

A primeira metade do manuscrito principal narrava uma estória muito peculiar. Aparentemente no dia 1 ° de março de 1925, um moço magro, moreno, de aspecto neurótico e excitado, visitou o professor Angell trazendo consigo o singular baixo-relevo de argila, que estava então recente e úmido. Seu cartão trazia o nome de Henry Anthony Wilcox e meu tio reconhecera-o como o filho mais novo de uma excelente família que ele conhecia superficialmente, e que estivera estudando escultura na Escola de Desenho de Rhode Island e vivendo sozinho no edifício Fleur-de-Lys perto daquela instituição. Wilcox era um jovem precoce de reconhecido talento porém grande excentricidade, e desde a infância despertara atenção devido às estórias esdrúxulas e aos sonhos bizarros que tinha o hábito de contar. Ele chamava a si mesmo de “psiquicamente hipersensível”, mas a gente convencional da antiga cidade comercial considerava-o apenas “esquisitão”. Sem nunca se misturar muito com os seus, gradualmente afastara-se do convívio social e só era conhecido de um pequeno grupo de estetas de outras cidades. Mesmo o Clube de Arte de Providence, ansioso por preservar seu conservadorismo, desistira de tê-lo entre seus membros.

Na ocasião da visita, continuava o manuscrito do professor, o escultor pediu abruptamente a assistência do conhecimento arqueológico de seu anfitrião para identificar os hieróglifos do baixo-relevo. Falava de um jeito sonhador e afetado que denotava pose e alienação; e foi com certa rispidez que meu tio respondeu-lhe, pois a notória frescura do tablete indicava relação com tudo menos com arqueologia. A réplica do jovem Wilcox, que impressionou meu tio o bastante para que este a recordasse e a registrasse textualmente, foi feita num tom fantasticamente poético que deve ter caracterizado toda a sua conversa e que desde então verifiquei ser bem próprio dele; ele disse: “Realmente é novo, pois o fiz na noite passada durante um sonho que tive com cidades estranhas; e sonhos são mais antigos do que a cismarenta Tiro, a contemplativa Esfinge ou a Babilônia dos jardins suspensos.”

Foi então que ele começou a narrativa desconexa que subitamente despertou uma memória adormecida e conquistou o interesse febril do meu tio. Um leve tremor de terra ocorrera na noite anterior, o mais intenso registrado na Nova Inglaterra em anos, e afetara vivamente a imaginação de Wilcox. Este, ao se recolher, tivera um sonho sem precedentes, com grandes cidades ciclópicas de blocos titânicos e monólitos que alcançavam o céu, todos gotejando lodo verde e impregnados de horror latente. Hieróglifos cobriam as paredes e colunas, e de algum ponto indeterminado, abaixo, vinha uma voz que não era uma voz, e sim uma sensação caótica que só a fantasia poderia transmudar em som, mas que ele tentou traduzir num amontoado quase impronunciável de letras: “Cthulhu fhtagn “.

Essa mixórdia verbal foi a chave para a lembrança que excitou e perturbou o professor Angell. Ele interrogou o escultor com minúcia científica e estudou com intensidade quase frenética o baixo-relevo no qual o rapaz se encontrara trabalhando, enregelado e apenas com suas roupas de dormir, quando acordou, atônito. Meu tio culpou sua velhice, Wilcox disse depois, por sua demora em reconhecer tanto os hieróglifos quanto o desenho pictórico. Muitas das perguntas dele pareceram altamente despropositadas ao visitante, especialmente as que tentavam relacionar a figura com cultos ou sociedades estranhas; e Wilcox não pôde compreender as repetidas promessas de silêncio que recebeu em troca de sua confissão de ser membro de alguma difundida irmandade mística ou pagã. Quando o professor Angell se convenceu de que o escultor realmente desconhecia qualquer culto ou sistema de ciência oculta, assediou seu visitante com pedidos de que viesse relatar-lhe futuramente os sonhos que voltasse a ter. Isso deu frutos regulares, pois após a primeira entrevista o manuscrito registra visitas diárias do rapaz, durante as quais ele narrava fragmentos surpreendentes de sua imagística noturna, centrada sempre num assustador panorama ciclópico de megalitos escuros e gotej antes, com uma voz ou inteligência subterrânea clamando monotonamente em enigmáticos impactos sensórios. Os dois sons mais freqüentemente repetidos eram aqueles traduzidos pelas letras ” Cthulhu ” e “R’lyeh “.

No dia 23 de março, continuava o manuscrito, Wilcox não apareceu; em sua residência informaram que ele havia sido acometido por uma espécie desconhecida de febre e levado para a casa de sua família na rua Waterman. Havia gritado à noite, acordando vários outros artistas do prédio, e manifestara desde então apenas alternações de inconsciência e delírio. Meu tio telefonou imediatamente para a família, e a partir daí acompanhou o caso de perto, indo muitas vezes ao consultório do Dr. Tobey, o médico encarregado, na Rua Thayer. A mente febril do rapaz aparentemente ocupava-se de coisas estranhíssimas, e o doutor de vez em quando estremecia ao falar delas. Essas coisas não somente repetiam o que ele sonhara antes, mas também incluíam uma coisa gigantesca “com milhas de altura” que caminhava ou se movia. Em nenhum momento descrevera o objeto, mas ocasionais palavras frenéticas, conforme repetidas pelo Dr. Tobey, convenceram o professor de que devia tratar-se da inominável monstruosidade que Wilcox procurara representar em sua escultura do sono. Referências a esse objeto, acrescentou o doutor, eram invariavelmente prelúdio à queda do rapaz na letargia. Sua temperatura, curiosamente, não estava muito acima da normal; mas todo o seu estado parecia indicar antes febre do que perturbação mental.

No dia 2 de abril, por volta das 3 da tarde, todos os sinais da enfermidade de Wilcox desapareceram subitamente. Sentou-se empertigado na cama, atônito por encontrar-se em casa e ignorando completamente o que acontecera em sonho ou realidade desde a noite de 22 de março. Tendo recebido alta do médico, voltou para o seu alojamento três dias depois; porém não foi mais de nenhuma serventia para o professor Angell. Todos os vestígios de sonhos bizarros haviam desaparecido com a convalescença, e meu tio não registrou mais seus sonhos após uma semana de relatos inúteis e irrelevantes de visões absolutamente normais.

Neste ponto terminava a primeira parte do manuscrito, mas referências a algumas das anotações dispersas deram-me muito o que pensar, tanto, na verdade, que somente o enraizado ceticismo que então constituía minha filosofia pode explicar o fato de que eu continuava duvidando do artista. As anotações em questão eram aquelas que descreviam os sonhos de várias pessoas durante o mesmo período em que o jovem Wilcox tivera as suas estranhas visões. Meu tio, ao que parece, havia rapidamente organizado um esquema prodigiosamente amplo de investigação entre quase todos os amigos que podia interrogar sem impertinência, pedindo-lhes relatos de seus sonhos de todas as noites e datas de quaisquer visões incomuns a partir de certo dia. A receptividade ao seu pedido parece ter variado; mas ele deve ter recebido, no mínimo, mais respostas do que um homem normal poderia dar conta sem uma secretária. Essa correspondência original não foi preservada, porém suas anotações constituíam um resumo abrangente e realmente significativo dela. As pessoas comuns da sociedade e do mundo dos negócios o tradicional “sal da terra” da Nova Inglaterra – deram um resultado quase completamente negativo, embora casos esparsos de impressões noturnas desagradáveis mas indefinidas apareçam aqui e ali, sempre entre 23 de março e 2 de abril – o período de delírio do jovem Wilcox. Os homens de ciência não foram afetados em grau muito maior, apesar de quatro casos de descrição vaga sugerirem vislumbres fugazes de paisagens estrambóticas, e de um caso mencionar certo pavor de algo anormal.

Foi dos artistas e poetas que as respostas pertinentes vieram, e tenho certeza de que o pânico teria se instaurado se eles tivessem podido comparar as anotações. Como eu não tinha as cartas originais, meio que suspeitei que o compilador houvesse feito perguntas tendenciosas ou organizado a correspondência em concordância com o que ele havia latentemente resolvido ver. Por essa razão continuei a achar que Wilcox, tendo tomado conhecimento das informações que o meu tio possuía, estivera pregando uma peça no veterano cientista. Essas respostas de estetas contavam uma história perturbadora. Entre 28 de fevereiro e 2 de abril uma grande proporção deles havia sonhado com coisas bizarras, sonhos cuja intensidade era incomensuravelmente maior durante o período do delírio do escultor. Cerca de um quarto das respostas falava de cenas e de sons que nada diferiam dos que Wilcox descrevera, e alguns desses sonhadores confessaram um medo agudo da coisa gigantesca e inominável visível no final. Um dos casos, que a anotação descreve com particular ênfase, era seríssimo. O indivíduo em questão, um arquiteto de grande renome, inclinado à teosofia e ao ocultismo, foi acometido de loucura violenta na data da crise do jovem Wilcox, e expirou vários meses mais tarde após gritar incessantemente que o salvassem das garras de uma besta que escapara do inferno. Se o meu tio tivesse se referido a esses casos por nome e não apenas por número, eu teria tentado obter alguma corroboração e feito alguma investigação pessoal; do jeito que estava, consegui localizar somente uns poucos missivistas. Todos estes, no entanto, confirmaram as anotações plenamente. Muitas vezes tenho me perguntado se todas as pessoas interrogadas pelo professor se sentiram tão perplexas quanto aquele grupo. Sorte deles nunca terem recebido explicação nenhuma.

Os recortes de jornal, como já disse, mencionavam casos de pânico, manias e excentricidades ocorridos durante o período em questão. O professor Angell deve ter empregado um escritório especializado na coleta de recortes, pois o número de artigos era tremendo, e as fontes espalhavam-se por todo o planeta. Um recorte falava de um suicídio noturno em Londres, onde um sonâmbulo pulara de uma janela após um grito lancinante. Outro consistia numa carta desconexa ao editor de um jornal na América do Sul, em que um fanático, baseado em visões que tivera, predizia um futuro calamitoso. Um despacho da Califórnia descrevia uma colônia de teosofistas envergando em massa túnicas brancas à espera de certo “glorioso advento” que nunca chegava, ao passo que notícias da índia falavam reservadamente sobre graves tumultos nativos por volta do fim de março. Orgias de vodu multiplicaram-se no Haiti e postos avançados na África reportaram murmúrios agourentos. Oficiais norte-americanos nas Filipinas encontraram hostilidade por parte de certas tribos nessa época e policiais de Nova Iorque foram atacados por multidões de levantinos histéricos na noite de 22 para 23 de março. O oeste da Irlanda também foi infestado de rumores inacreditáveis e lendas, e um pintor fantástico chamado Ardois-Bonnot exibiu um delirante quadro intitulado Paísagem Onírica no salão de primavera de Paris de 1926.E tão numerosos são os tumultos registrados em hospícios que só por milagre a fraternidade médica deixou de notar estranhos paralelismos e tirar conclusões mistificadas. Em suma, um surpreendente punhado de recortes, e é com assombro que me lembro hoje do empedernido racionalismo com que os pus de lado. Mas eu estava então convencido de que o jovem Wilcox tivera conhecimento dos assuntos antigos mencionados pelo professor.

II. O RELATO DO INSPETOR LEGRASSE

Os assuntos antigos que haviam feito o sonho e o baixo-relevo do escultor tão significativos para o meu tio constituíam o tema da segunda metade do seu longo manuscrito. Parece que anteriormente o professor Angell tinha visto uma vez os contornos infernais da inominada monstruosidade, confundira-se diante dos hieróglifos desconhecidos e escutara as agourentas sílabas que só podem ser grafadas como “Cthulhu”; e tudo isso interligado de forma tão espantosa e horrível, que não é de admirar que tenha perseguido o jovem Wilcox com perguntas e exigências de informações.

Essa prévia experiência ocorrera em 1908, dezessete anos antes, quando a Sociedade Arqueológica Americana realizou seu encontro anual em Saint Louis. O professor Angell, como convinha a alguém de sua autoridade e realizações, tivera um papel proeminente em todas as deliberações, e foi um dos primeiros a serem abordados por diversos leigos que aproveitaram a oportunidade para fazer perguntas e pedir opinião de peritos sobre certos problemas.

O principal desses leigos, que em breve se tornaria o foco de interesse de toda a reunião, foi um homem de meia-idade e aparência convencional que tinha viajado desde Nova Orleans para obter certa informação especial impossível de obter de qualquer fonte local. Seu nome era John Raymond Legrasse e sua profissão era a de inspetor de polícia. Trazia com ele a razão de sua visita, uma grotesca, repulsiva e aparentemente antiquíssima estatueta de pedra cuja origem não conseguia determinar.

Não se deve imaginar que o inspetor Legrasse tivesse o menor interesse em arqueologia; ao contrário, seu desejo de esclarecimento era movido por considerações puramente profissionais. A estatueta, ídolo, fetiche ou o que quer que fosse, fora capturada alguns meses antes nas florestas pantanosas do sul de Nova Orleans durante uma batida policial num suposto culto de vodu; e tão singulares e medonhos eram os ritos ligados à peça, que a polícia de imediato percebeu que dera de cara com um culto sinistro totalmente desconhecido para eles e infinitamente mais diabólico que o mais negro dos círculos africanos de vodu. Sobre a sua origem, além das estórias esdrúxulas e inacreditáveis arrancadas aos membros capturados, absolutamente nada pôde ser descoberto. Daí a ansiedade da polícia por qualquer conhecimento de coisas antigas que pudesse ajudá-la a identificar o símbolo aterrador e, através dele, descobrir a fonte daquele culto.

O inspetor Legrasse não estava de forma alguma preparado para a sensação que a sua intervenção causou. Um simples olhar ao objeto fora suficiente para lançar os homens de ciência ali reunidos num estado de tensa excitação, e eles não perderam tempo em se amontoar ao redor dele para encarar de perto a diminuta imagem cuja profunda estranheza e aparência de antigüidade genuína e abismal indicavam panoramas arcaicos ainda por revelar. Nenhuma escola conhecida de escultura animara aquele terrível objeto, e no entanto séculos, até milênios pareciam gravados em sua baça e esverdeada superfície de pedra não identificada.

A imagem, que foi finalmente passada devagar de mão em mão para exame mais atento e cuidadoso, tinha entre quinze e dezoito centímetros de altura e era de elaborado artesanato. Representava um monstro vagamente antropóide, mas com uma cabeça semelhante à de um polvo e cujo rosto era uma massa de tentáculos, de corpo escamoso com aspecto elástico, prodigiosas garras nas patas dianteiras e traseiras, e asas longas e estreitas atrás. Essa coisa, que parecia imbuída de assustadora e inatural malignidade, tinha uma corpulência algo intumescida e estava agachada ameaçadoramente sobre um bloco retangular ou pedestal coberto de caracteres indecifráveis. As pontas das asas tocavam a beirada traseira do bloco, o assento ocupava o centro e as compridas e recurvadas garras das patas traseiras dobradas sobre si mesmas, agarravam a beirada dianteira e estendiam-se por um quarto da altura do pedestal. A cabeça cefalópode estava inclinada para frente, de modo que as extremidades dos tentáculos faciais varriam as costas das maciças patas dianteiras que agarravam os joelhos dos membros traseiros. 0 aspecto geral era anormalmente vivido, e ainda mais sutilmente assustador pelo fato de sua origem ser totalmente desconhecida. Embora sua vasta, espantosa e incalculável antigüidade fosse inegável, a estatueta não apresentava ligação com nenhum tipo de arte pertencente à mocidade da civilização, ou, na verdade, a qualquer época.

O seu próprio material era um mistério, pois a pedra lisa e negro-esverdeada com pintas douradas ou iridescentes e estrias não se assemelhava a nada familiar à geologia ou à mineralogia. Os caracteres ao longo da base eram igualmente intrigantes, e nenhum dos cientistas ali presentes, apesar de representarem metade do conhecimento mundial nesse campo, teve a menor noção sequer da mais remota filiação lingüística deles. Tal como o tema e o material, esses caracteres pertenciam a alguma coisa horrivelmente distante e alheia à humanidade como a conhecemos, algo que sugeria de forma assustadora antigos e profanos ciclos de vida dos quais nosso mundo e nossas concepções não fazem parte.

No entanto, enquanto os vários cientistas balançavam a cabeça e admitiam-se derrotados perante o enigma trazido pelo inspetor, havia na reunião um homem a quem pareceram estranhamente familiares aquelas monstruosas forma e escrita, e que então falou com certa hesitação do pouco que sabia a respeito. Ele era o falecido William Channing Webb, professor de antropologia na Universidade de Princeton e explorador de considerável renome.

O professor Webb participara, quarenta e oito anos antes, de uma expedição à Groenlândia e à Islândia em busca de inscrições rúnicas, que não conseguiu achar; e ao percorrer a costa oeste da Groenlândia havia encontrado uma singular tribo de esquimós degenerados cuja religião, uma curiosa forma de culto ao diabo, provocou-lhe calafrios com sua repelência e deliberada sede de sangue. Tratava-se de um credo do qual os outros esquimós pouco sabiam, e que só mencionavam com estremecimentos de horror, dizendo que vinha de eras terrivelmente antigas, anteriores à criação do mundo. Além de ritos inenarráveis e sacrifícios humanos, havia alguns esquisitos rituais hereditários dirigidos a um supremo diabo ancião ou tornasuk, dos quais o professor Webb fizera uma cuidadosa transcrição fonética com a ajuda de um idoso angekok ou bruxo-sacerdote, grafando os sons em caracteres romanos o melhor que pôde. Porém, o que mais interessava era o fetiche que esse culto idolatrava e em torno do qual dançavam quando a aurora boreal lambia os picos gelados. Segundo declarou o professor, tratava-se de um tosco baixo relevo de pedra que compreendia uma figura medonha e algumas inscrições crípticas; e, até onde podia afirmar, coincidia, nos aspectos essenciais, com a coisa bestial que se tornara centro das atenções na reunião.

Essas informações, recebidas com assombro e emoção pelos presentes à reunião, foram ainda mais emocionantes para o inspetor Legrasse, que imediatamente começou a assediar o seu informante com perguntas. Tendo anotado e transcrito um ritual oral entre os sectários brejeiros que seus homens haviam prendido, pediu ao professor que procurasse lembrar o melhor que pudesse das sílabas anotadas entre os esquimós diabolistas. Seguiu-se então uma exaustiva comparação de detalhes e um momento de boquiaberto silêncio, quando tanto o detetive quanto o cientista concordaram na identidade virtual da frase comum aos dois ritos infernais tão distantes um do outro como se pertencessem a mundos diferentes. O que, essencialmente, tanto os bruxos esquimós quanto os sacerdotes brejeiros da Louisiana entoavam aos seus ídolos era algo semelhante ao que vai abaixo, sendo as divisões entre palavras supostas por analogia com as quebras tradicionais na frase quando cantada em voz alta:

“Ph’nglui mglw’nafh Cthulhu R’lyeh wgah’naglfhtagn.”

Nesse ponto Legrasse levava vantagem sobre o professor Webb, pois vários dos seus prisioneiros mestiços haviam-lhe repetido o que celebrantes mais velhos haviam-lhes dito sobre o significado dessas palavras. Esse texto dizia mais ou menos o seguinte:

“Na sua casa em R’lyeh, Cthulhu morto espera sonhando.”

Então, em resposta às urgentes solicitações de todos, o inspetor Legrasse narrou, tão detalhadamente quanto possível, sua experiência com os idólatras dos pântanos, contando uma estória à qual pude ver que o meu tio atribuía enorme importância. Fazia lembrar os sonhos mais desvairados dos mitômanos e teosofistas, além de revelar um grau surpreendente de imaginação cósmica, que nunca se esperaria entre aqueles marginais e párias da sociedade.

No dia 1 ° de novembro de 1907 chegara à polícia de Nova Orleans um chamado frenético da região de pântanos e lagoas ao sul. Os grileiros de lá, na maioria descendentes primitivos, mas de boa índole, dos homens de Lafitte, estavam tomados do mais absoluto pânico por causa de uma coisa desconhecida que viera sobre eles à noite. Tratava-se de vodu, aparentemente, mas de uma espécie de vodu muito mais terrível do que qualquer outra que já tinham visto; e algumas de suas mulheres e crianças haviam desaparecido desde que o malévolo tantã começara a bater incessantemente bem para dentro das sombrias florestas, onde nenhum morador da região se aventurava. Ouviam-se gritos insanos e berros apavorantes, cânticos que gelavam o sangue e chamas demoníacas que bruxuleavam; e ninguém mais suportava aquilo, acrescentou o assustado mensageiro.

Então um grupo de vinte policiais, em duas carruagens e um automóvel, havia partido no Fim da tarde com o trêmulo grileiro como guia. No fim da estrada transitável desceram e chapinharam por milhas em silêncio, em meio aos terríveis bosques de ciprestes onde nunca raiava o dia. Medonhas raízes e malignas barbas-de-velho dificultavam a caminhada, e de vez em quando uma pilha de pedras úmidas ou fragmentos de uma parede apodrecida intensificavam, com sua sugestão de povoação sórdida, uma angústia que cada árvore mal formada e a profusão de fungos contribuía para criar. Por fim, a aldeia dos grileiros, um ajuntamento miserável de cabanas, ficou à vista, e moradores histéricos acorreram para refugiar-se em volta do grupo de lanternas balouçantes. O som abafado dos tantãs já se ouvia ao longe, bem longe; e um grito agudo como um guincho vinha em intervalos desiguais quando o vento mudava de direção. Também um clarão avermelhado parecia filtrar-se através da pálida vegetação rasteira, oriundo de avenidas intermináveis de noite selvagem. Todos os assustados grileiros recusaram-se terminantemente a dar um passo sequer rumo àquele culto ímpio, de modo que o inspetor Legrasse e seus dezenove colegas embrenharam-se sem guia nas arcadas negras de terror pelas quais nenhum deles jamais passara antes.

A região em que agora se aventuravam os policiais era tradicionalmente de má reputação, desconhecida e inexplorada pelos brancos. Corriam lendas sobre um lago oculto nunca contemplado por mortais, no qual vivia uma gigantesca e disforme criatura poliposa branca com olhos luminosos; e os grileiros sussurravam que diabos com asas de morcego voavam para fora de cavernas nas entranhas da terra à meia-noite para adorar aquele ser. Diziam que ele estivera lá antes de D’Iberville, antes de La Salle, antes dos índios e antes mesmo dos saudáveis animais e pássaros das florestas. A criatura era o pesadelo encarnado e vê-la significava morrer. Mas também fazia os homens sonharem, por isso sabiam que deviam manter-se afastados. A atual orgia vodu ocorria, de fato, no limite daquela área amaldiçoada, daí o próprio local do culto ter talvez aterrorizado os grileiros mais do que os sons chocantes e os incidentes.

Só a poesia ou a loucura poderiam descrever fielmente os barulhos ouvidos pelos homens de Legrasse ao avançarem pelos atoleiros negros rumo ao clarão vermelho e aos tantãs abafados. Existem sons característicos de homens e característicos de bestas, e é pavoroso escutar um quando a fonte deveria produzir o outro. A fúria animal e a licenciosidade orgiástica ali eram atiçadas a níveis demoníacos por uivos e êxtases guinchantes que reverberavam por aqueles bosques cobertos de noite como tempestades pestilenciais emanadas dos abismos do inferno. De vez em quando as ululações menos organizadas cessavam, e do que parecia um coro bem treinado de vozes roucas, elevava-se como uma ladainha aquela frase ou ritual nefando:

“Ph’nglul’ mglw’nafh Cthulhu R’lych wgah’naglfhtagn. “

Foi então que os homens, tendo alcançado um local onde as árvores eram mais finas, de repente avistaram o próprio espetáculo. Quatro deles cambalearam, um desfaleceu e dois emitiram um grito frenético que a louca cacofonia da orgia afortunadamente encobriu. Legrasse jogou água do pântano no rosto do homem desmaiado e todos ficaram trêmulos e quase hipnotizados de horror.

Numa clareira natural do pântano havia uma ilha de relva com cerca de meio hectare, sem árvores e toleravelmente seca. Nela saltava e se retorcia uma indescritível horda de anormalidade humana, que só um Sime ou um Angarola poderiam pintar. Sem roupa alguma, aquelas criaturas híbridas zurravam, berravam e se contorciam ao redor de uma monstruosa fogueira circular, no meio da qual erguia-se, revelado por ocasionais frestas na cortina de chamas, um imponente monólito de granito com uns dois metros e meio de altura; em cima dele, numa pequenez incongruente, jazia a nefasta estatueta. De um amplo círculo de dez cadafalsos dispostos a intervalos regulares, com o monólito cingido de chamas ao centro, pendiam de ponta-cabeça os corpos atrozmente mutilados dos indefesos grileiros que haviam desaparecido. Era dentro desse círculo que a roda de adoradores pulava e rugia da esquerda para a direita numa bacanal sem fim entre o anel de cadáveres e o anel de fogo.

Pode ter sido só imaginação, como podem ter sido apenas ecos, que induziram um dos homens, um excitável hispânico, a julgar ter ouvido respostas antifonais ao ritual, vindas de um distante e penumbroso ponto no fundo da floresta de antigas lendas e horrores. Mais tarde encontrei e interroguei esse homem, Joseph D. Galvez, que mostrou ter uma imaginação delirante; de fato, ele chegou ao extremo de sugerir ter escutado um leve rufiar de grandes asas e vislumbrado olhos fulgurantes bem como um montanhoso vulto branco além das árvores remotas mas eu suponho que ele andara assimilando muita superstição local.

Na verdade, a pausa horrorizada dos homens foi de duração relativamente curta. O dever vinha em primeiro lugar; e embora houvesse quase cem celebrantes naquela horda, a polícia confiou em suas armas de fogo e investiu resolutamente contra a nauseante turba. Por cinco minutos o alarido e o caos resultantes foram indescritíveis. Golpes selvagens foram vibrados, tiros foram disparados e fugas ocorreram, mas no final Legrasse pôde contar uns quarenta e sete soturnos prisioneiros, os quais forçou a vestirem-se depressa e formar uma fila entre duas fileiras de policiais. Cinco dos adoradores jaziam mortos e dois gravemente feridos foram carregados em padiolas improvisadas por seus camaradas. A imagem sobre o monólito foi, é lógico, cuidadosamente removida e levada embora por Legrasse.

Interrogados na chefatura de polícia após uma jornada tensa e extenuante, verificou-se que todos os prisioneiros eram de classe social ínfima, mestiços e mentalmente perturbados. A maioria era de marinheiros, e um magote de negros e mulatos, quase todos das índias Ocidentais ou portugueses das ilhas de Cabo Verde, dava uma tintura de vodu ao culto heterogêneo. Antes, porém, que muitas perguntas fossem feitas, ficou claro que se tratava de algo muito mais profundo e antigo do que o fetichismo negro. Degradadas e ignorantes que eram, aquelas criaturas atinham-se com surpreendente consistência à idéia central de seu credo abominável.

Eles adoravam, segundo disseram, os Grandes Antigos, que viveram muitas eras antes da existência do homem e que chegaram ao recém-criado mundo vindos do céu. Esses Antigos haviam agora desaparecido no interior da terra e sob o mar; porém, mesmo mortos, haviam transmitido seus segredos em sonhos ao primeiro homem, que instaurou um culto que jamais morrera. Era esse o culto que professavam, e os prisioneiros afirmaram que ele sempre existira e sempre existiria, oculto em distantes locais desertos e sombrios por todo o mundo, até o tempo em que o sumo sacerdote Cthulhu, de sua escura morada na poderosa cidade de R’lyeh, sob as águas do mar, se levantasse e pusesse de novo a terra sob seu domínio. Um dia ele chamaria, quando as estrelas estivessem prontas, e o culto secreto estaria sempre à espera para libertá-lo.

Até lá, nada mais seria dito. Havia um segredo que nem a tortura poderia extrair. A humanidade não estava de forma alguma sozinha entre os seres conscientes da terra, pois formas saíam das trevas para visitar os poucos fiéis. Mas esses não eram os Grandes Antigos. Nenhum homem jamais vira os Antigos. O ídolo esculpido representava o grande Cthulhu, mas ninguém poderia dizer se os outros eram ou não exatamente como ele. Ninguém era capaz hoje em dia de ler a antiga escrita, porém as coisas eram transmitidas por tradição oral. O cântico ritual não era o segredo – este nunca era falado em voz alta, apenas sussurrado. O cântico significava apenas isto: “Na sua casa em R’lyeh, Cthulhu morto espera sonhando”.

Apenas dois dos prisioneiros foram considerados sãos o bastante para serem enforcados; os demais foram internados em diversas instituições. Todos negaram participação nos assassinatos rituais e asseveraram que estes haviam sido obra dos Asas Negras, que tinham vindo a eles oriundos do seu imemorial ponto de encontro na floresta assombrada. Mas desses misteriosos aliados nenhum relato coerente pôde ser obtido. A maior parte do que a polícia conseguiu averiguar veio de um mestiço fabulosamente idoso chamado Castro, que afirmava ter viajado a portos longínquos e falado com líderes imortais do culto nas montanhas da China.

O velho Castro recordava-se de fragmentos de medonhas lendas que empalideciam as especulações dos teosofistas e faziam homem e mundo parecerem recentes e efêmeros. Houve épocas em que outros Seres dominavam a terra, e Eles haviam erigido cidades colossais. De acordo com o que os chineses imortais lhe haviam dito, vestígios desses Seres podiam ainda ser encontrados nas rochas ciclópicas em ilhas do Pacífico. Todos Eles haviam morrido muitas eras antes da chegada do homem, mas havia artes capazes de fazê-los reviver quando as estrelas retornassem às posições certas no ciclo da eternidade. Eles mesmos tinham vindo das estrelas e trazido consigo Suas imagens.

Esses Grandes Antigos, prosseguiu Castro, não se compunham inteiramente de carne e ossos. Tinham forma – não o provava aquela imagem talhada nas estrelas? -, mas essa forma não era feita de matéria. Quando as estrelas assumiam a configuração correta, Eles podiam transportar-se de um mundo para outro pelo espaço sideral; mas quando as estrelas não eram favoráveis, Eles não podiam viver. Contudo, embora já não vivessem, Eles nunca verdadeiramente morriam. Jaziam todos em suas moradas de pedra na grande cidade de R’lyeh, preservados pelos encantamentos do poderoso Cthulhu para uma gloriosa ressurreição quando as estrelas e a terra estivessem mais uma vez prontas para Eles. Chegado esse tempo, porém, alguma força exterior precisaria liberar Seus corpos. Os encantamentos que Os preservavam intactos também Os impediam de fazer o movimento inicial, e tudo que podiam fazer era ficar despertos nas trevas e meditar, enquanto milhões de anos se escoavam. Sabiam de tudo o que acontecia no universo, pois comunicavam-se por telepatia. Mesmo naquele instante conversavam em Suas tumbas. Quando, após infindáveis eras de caos o primeiro homem surgiu, os Grandes Antigos falaram aos mais sensíveis dentre eles dando forma aos seus sonhos, pois só assim Sua linguagem conseguia alcançar as mentes carnosas dos mamíferos.

Em seguida, sussurrou Castro, aqueles primeiros homens formaram o culto ao redor de pequenos ídolos que os Grandes lhes haviam mostrado, ídolos trazidos de estrelas sombrias na noite dos tempos. Aquele culto jamais morreria até que as estrelas ficassem propícias de novo, e então os sacerdotes secretos tirariam o grande Cthulhu da Sua tumba para que Este fizesse reviver os Seus súditos e retomasse o Seu domínio sobre a terra. O tempo seria fácil de reconhecer, pois por essa época a humanidade já teria se tornado como os Grandes Antigos: livres, selvagens, além do bem e do mal, ignorando leis e preceitos morais, com todo mundo gritando, matando e farreando em meio a feroz alegria. Então os Antigos, libertados, ensinar-lhes-iam novas formas de berrar e matar e farrear com alegria desenfreada, e toda a terra se inflamaria num holocausto de êxtase e liberdade. Até lá, cabia ao culto, mediante ritos apropriados, manter viva a memória daqueles procedimentos antediluvianos e prefigurar a profecia da volta d’Eles.

Em priscas eras homens eleitos haviam falado com os sepultados Antigos em sonhos, mas então algo acontecera: a grande cidade de pedra de R’lyeh, com seus monólitos e sepulcros, afundara sob as ondas, e as águas profundas, repletas do único mistério primordial que nem o pensamento pode atravessar, haviam interrompido o intercâmbio espectral. Mas a memória nunca morreu, e os sumos sacerdotes diziam que a cidade emergiria de novo quando as estrelas se alinhassem corretamente. Então vieram das profundezas da terra os seus espíritos negros, bolorentos e trevosos, cheios de rumores ancestrais colhidos em cavernas sob esquecidos leitos oceânicos. Mas deles o velho Castro não ousou falar muito. Calou-se apressadamente, e não houve persuasão ou sutileza capaz de extrair-lhe mais informações sobre o assunto. Curiosamente, evitou também mencionar o tamanho dos Antigos. A respeito do culto, afirmou crer que sua sede ficava nos desertos inacessíveis da Arábia, onde Irem, a Cidade dos Pilares, sonha oculta e intacta. Não tinha relação com os cultos de bruxaria europeus e, exceto por seus membros, era virtualmente desconhecido. Nenhum livro jamais aludiu diretamente a ele, embora os chineses imortais dissessem que havia duplos sentidos no Necronomicon, do árabe louco Abdul Alhazred, que os iniciados poderiam interpretar como quisessem, especialmente o polêmico dístico:

Não está morto o que pode eternamente jazer, E com estranhas eras pode até a morte morrer.

Legrasse, bastante impressionado e não pouco estupefato, havia investigado em vão sobre as afiliações históricas do culto. Aparentemente Castro dissera a verdade ao afirmar que era totalmente secreto. As autoridades da Universidade de Tulane não puderam dar esclarecimento algum tanto a respeito do culto quanto da imagem, e agora o detetive viera consultar as maiores autoridades do país, sem nada obter além da estória da Groenlândia contada pelo professor Webb.

O interesse febril despertado na reunião por Legrasse e sua narrativa, corroborada pela estatueta, encontra eco na subseqüente correspondência dos que estavam presentes, embora haja escassa menção ao incidente na publicação formal da sociedade. Cautela é a preocupação máxima daqueles que estão acostumados à charlatanice e impostura ocasionais. Legrasse emprestou a imagem por algum tempo ao professor Webb, mas com a morte deste, foi-lhe devolvida e com ele permanecia quando a vi, não faz muito tempo.  É uma coisa verdadeiramente medonha,  e inequivocamente aparentada à escultura sonhada e esculpida pelo jovem Wilcox.

Não me surpreendeu que a narrativa do escultor tivesse alvoroçado o meu tio, pois que idéias poderiam ocorrer-lhe, após saber o que Legrasse descobrira sobre o culto, ao ouvir um rapaz sensível dizer-lhe que sonhara não somente a figura e os hieróglifos exatos da imagem encontrada no pântano e do demoníaco baixo-relevo da Groenlândia, como também escutara em seus sonhos pelo menos três das palavras precisas da fórmula emitida tanto pelos diabolistas esquimós quanto pelos mestiços da Louisiana? Foi a coisa mais natural que o professor Angell iniciasse uma investigação aprofundada, ainda que eu privadamente suspeitasse que o jovem Wilcox ouvira falar do culto de maneira indireta e tivesse inventado uma série de sonhos para intensificar e manter o mistério, às custas do meu tio. As narrativas de sonhos e os recortes coletados pelo professor eram, é claro, forte corroboração; mas o meu racionalismo e a extravagância da coisa toda levaram-me a adotar o que julguei ser a conclusão mais sensata. Assim, depois de estudar detidamente o manuscrito mais uma vez e de correlacionar as anotações teosóficas e antropológicas na narrativa feita por Legrasse sobre o culto, fiz uma viagem a Providence para ver o escultor e repreendê-lo devidamente por divertir-se às custas de um homem letrado e idoso.

Wilcox ainda vivia sozinho no edifício Fleur-de-Lys, na Rua Thomas, uma hedionda imitação vitoriana da arquitetura bretã do século xv1, que pavoneia sua fachada de estuque em meio às lindas casas coloniais na antiga colina, e à sombra do mais esplêndido campanário georgiano dos Estados Unidos. Encontrei-o trabalhando em seus aposentos, e de imediato constatei, a julgar pelas suas peças espalhadas, que seu talento era de fato profundo e original. Acredito que um dia ele será aclamado como um dos grandes decadentistas, pois cristalizou na argila e um dia refletirá no mármore os pesadelos e fantasias que Arthur Machen evoca na prosa e Clark Ashton Smith torna visível no verso e na pintura.

Moreno, franzino e de aspecto algo desleixado, ele se voltou languidamente ao me ouvir bater à porta e, sem se levantar, perguntou-me a que vinha. Quando eu lhe disse quem eu era, ele demonstrou certo interesse; pois meu tio despertara-lhe a curiosidade ao investigar seus sonhos estranhos, embora nunca tivesse explicado a razão do seu interesse. Eu tampouco expliquei, mas procurei sutilmente fazer com que se abrisse comigo.

Em pouco tempo fiquei convencido da sua absoluta sinceridade, pois falou nos sonhos de um modo inequívoco. Os sonhos e o resíduo subconsciente deles haviam influenciado profundamente a sua arte, e ele me mostrou uma estátua mórbida cujos contornos quase me fizeram estremecer com a força de seu poder de negra evocação. Não se lembrava de ter visto o original daquilo, exceto no seu próprio baixo-relevo onírico, mas os contornos haviam-se formado insensivelmente sob suas mãos. Era, sem dúvida, o vulto gigantesco que ele entrevira no seu delírio. Deixou claro nada saber sobre o culto secreto, salvo o que o infatigável interrogatório do meu tio deixara escapar; e de novo me esforcei por imaginar algum modo pelo qual ele pudesse ter recebido as estranhas impressões.

Falou de seus sonhos num modo estranhamente poético, fazendo-me ver com assustadora nitidez a úmida cidade ciclópica de lodosa pedra verde (cuja geometria, ele enfatizou singularmente, estava “toda errada”) e escutar com apavorada expectativa a evocação incessante e quase mental oriunda do subterrâneo da terra: “Cthulhu fhtagn”, “Cthulhu lhtagn”.

Essas palavras tinham feito parte daquele ritual macabro que falava do morto Cthulhu à espera, sonhando, na sua tumba de pedra em R’lyeh, e senti-me profundamente abalado, apesar do meu racionalismo. Eu tinha certeza de que Wilcox ouvira falar no culto por acaso, mas logo se esquecera dele em meio à massa de suas leituras e imaginação igualmente bizarras. Mais tarde, em virtude da impressionabilidade do moço, a lembrança achara expressão subconsciente em sonhos, no baixo-relevo e na medonha estátua que eu agora via, de modo que sua impostura sobre o meu tio fora totalmente inocente. O rapaz, ao mesmo tempo meio afetado e ligeiramente mal-educado, não era do tipo que eu jamais poderia vir a gostar; mas eu estava ao menos disposto a reconhecer tanto o seu gênio quanto a sua honestidade. Despedi-me dele amigavelmente, desejando-lhe todo o sucesso que seu talento promete.

A questão do culto continuava a me fascinar, e às vezes eu tinha visões de fama pessoal obtida graças a pesquisas sobre sua origem e conexões. Visitei Nova Orleans, conversei com Legrasse e outros participantes da batida policial, vi a monstruosa imagem e até entrevistei alguns prisioneiros mestiços ainda vivos; o velho Castro, infelizmente, já morrera havia alguns anos. O que ouvi então, de forma tão nítida e em primeira mão, embora não fosse mais que uma confirmação detalhada daquilo que meu tio escrevera, voltou a me estimular, pois tive a certeza de estar na pista de uma religião muito real, muito secreta e muito antiga, cuja descoberta faria de mim um antropólogo de renome. Minha atitude era ainda de absoluto materialismo, como gostaria que ainda fosse, e descartei com inexplicável má vontade a coincidência entre os relatos de sonhos e os esquisitos recortes colecionados pelo professor Angell.

Uma coisa que comecei a suspeitar e que agora infelizmente eu sei; é que a morte do meu tio nada teve de natural. Ele caiu de uma ladeira estreita que saía de um antigo cais repleto de mestiços estrangeiros, após um descuidado empurrão de um marinheiro negro. Não esqueci o sangue misto e atividades navais dos membros do culto na Louisiana, e não me surpreenderia se viesse a ouvir falar de métodos secretos e agulhas envenenadas tão implacáveis e antigas quanto os rituais e credos crípticos. É verdade que Legrasse e seus homens foram deixados em paz; mas na Noruega, um certo homem do mar, que viu coisas, morreu. Será que as investigações mais profundas do meu tio, após o encontro com o escultor, não poderiam ter chegado a ouvidos sinistros? Eu acho que o professor Angell morreu porque sabia demais ou estava prestes a saber demais. Se terei o mesmo fim que ele, é o que me resta saber, pois agora eu também sei demais.

III. A LOUCURA QUE VEIO DO MAR

Se aprouver aos céus conceder-me algum dia uma bênção, pedirei que seja o esquecimento total dos resultados do mero acaso que fixou meus olhos num certo pedaço perdido de papel que forrava uma prateleira. Não era algo com que eu normalmente tropeçaria no curso da minha rotina diária, pois tratava-se de um velho número de um jornal australiano, o Sydney Bulletin, de 18 de abril de 1925. A notícia escapara até mesmo ao escritório de recortes que, na época de sua publicação, coletava avidamente material para a pesquisa do meu tio.

Eu havia praticamente deixado de lado minhas investigações sobre o que o professor Angell chamava “Culto de Cthulhu”, e estava visitando um letrado amigo em Paterson, Nova Jersey, curador de um museu local e renomado mineralogista. Um dia, examinando amostras de reserva colocadas desordenadamente sobre as prateleiras de uma sala nos fundos do museu, meu olhar foi atraído por uma estranha gravura num dos velhos jornais espalhados debaixo das pedras. Era o exemplar do Sydney Bulletin a que me referi, pois meu amigo tinha amplas ligações em todos os países imagináveis; e a figura era uma litografia de uma horrorosa estatueta de pedra quase idêntica à que Legrasse encontrara no pântano.

Ansiosamente afastando da folha de jornal os preciosos espécimes minerais, estudei a notícia detalhadamente, mas fiquei desapontado ao ver que não era muito extensa. O que sugeria, no entanto, era de imensa importância para minha investigação algo desalentada, e rasguei cuidadosamente o recorte a fim de empreender ação imediata. Dizia o seguinte:

NAVIO ABANDONADO ENCONTRADO NO MAR

Vigilant chega rebocando iate neozelandês armado e avariado. Encontrados a bordo um sobrevivente e um morto. Estória de batalha desesperada e mortes em alto-mar. Marinheiro salvo recusa-se a dar detalhes da estranha experiência. Misterioso ídolo achado em seu poder. Será aberto Inquérito.

O cargueiro da Morrison Co., Vigilant, proveniente de Valparaíso, atracou esta manhã no porto de Darling, trazendo a reboque o avariado e inutilizado, mas fortemente armado, iate a vapor Alert, com matrícula de Dunedin, N. Z., que fora avistado no dia 12 de abril na latitude sul 34° 21′, longitude oeste 152° 17′, com um homem vivo e um morto a bordo.

O Vigilant deixou Valparaíso a 25 de março e, no dia 2 de abril, sua rota foi consideravelmente desviada para sul por fortíssimas tempestades e ondas monstruosas. Em 12 de abril foi avistado o barco à deriva, e embora aparentemente abandonado pela tripulação, foram encontrados a bordo um sobrevivente em estado de semi-delírio e um homem com evidências de estar morto há mais de uma semana.

O sobrevivente agarrava um horrível ídolo de pedra de origem desconhecida e cerca de um pé de altura, a respeito de cuja natureza as autoridades da Universidade de Sydney, da Royal Society e do Museu de College Street confessaram a mais absoluta ignorância, e que o sobrevivente afirma ter encontrado na cabina do iate, num pequeno relicário esculpido, de formato comum.

Após recuperar a consciência, esse homem narrou uma estória excessivamente estranha de pirataria e chacina. Seu nome é Gustaf Johansen, norueguês de alguma instrução, e servira como segundo-oficial da escuna Emma, de Auckland, que zarpou de Callao a 20 de fevereiro, com tripulação de onze homens.

A Emma, disse ele, foi retardada e largamente desviada de seu curso na direção sul pela grande tempestade de 1° de março; no dia 22 desse mês, na latitude sul 49° 51′ e longitude oeste 128° 34′, encontrou o Alert, tripulado por um esquisito e mal-encarado grupo de canacas e mestiços. Recebendo ordem peremptória de voltar, o capitão Collins recusou-se, ao que o estranho grupo abriu fogo violentamente e sem aviso sobre a escuna, com uma bateria peculiarmente pesada de canhões de bronze que faziam parte do equipamento do iate.

Os homens da Emma reagiram, prosseguiu o sobrevivente, e embora a escuna começasse a afundar devido a tiros que a atingiram abaixo da linha de flutuação, conseguiram abordar a embarcação inimiga e lutar corpo a corpo com os selvagens sobre o convés do iate, sendo forçados a matá-los todos, o número destes sendo ligeiramente maior, por causa de seu modo feroz e desesperado, ainda que despreparado, de lutar.

Três homens da Emma, incluindo o capitão Collins e o primeiro-oficial Green, foram mortos, e os oito restantes, sob comando do segundo-oficial Johansen, prosseguiram viagem no iate capturado, seguindo na direção original a fim de constatar se havia alguma razão para a ordem de retornar que tinham recebido.

No dia seguinte, ao que parece, desembarcaram numa pequena ilha, embora não conste a existência de ilha alguma naquela parte do oceano. Seis homens morreram em terra, ainda que Johansen seja estranhamente reticente sobre essa parte da estória, limitando-se a afirmar que caíram num abismo rochoso.

Parece que mais tarde ele e um companheiro voltaram ao iate e tentaram prosseguir viagem, mas foram atingidos pela tempestade do dia 2 de abril.

A partir desse dia até seu resgate no dia 12, o homem se lembra de pouca coisa, e não se recorda sequer de quando William Briden, seu companheiro, morreu. A morte de Briden não revela causa aparente e provavelmente deveu-se a choque emocional ou exposição contínua às intempéries.

Notícias recebidas de Dunedin informam que o Alert era bem conhecido por lá como navegador de cabotagem e que gozava de má reputação nos meios marítimos. Era de propriedade de um curioso grupo de mestiços cujas freqüentes reuniões e viagens noturnas aos bosques despertavam considerável curiosidade; zarpara com grande pressa logo depois da tempestade e dos tremores de terra de 1° de marco.

Nosso correspondente em Auckland atribui à Emma e sua tripulação uma reputação excelente, e Johansen é descrito como homem sóbrio e valoroso.

Amanhã o almirantado abrirá inquérito sobre o incidente, no qual serão feitos todos os esforços para induzir Johansen a falar mais do que até o momento.

Isso era tudo, juntamente com a foto da imagem infernal; mas que sucessão de idéias desencadeou na minha mente! Aqui estavam novos tesouros de informação sobre o Culto de Cthulhu, bem como evidências de que possuía estranhos interesses no mar tanto quanto em terra. Que motivo levara a tripulação de mestiços a ordenar o retorno da Emma enquanto navegavam com aquele medonho ídolo? Qual era a ilha desconhecida onde seis membros da tripulação da Emma haviam morrido e sobre a qual o imediato Johansen guardava tanto segredo? O que haveria descoberto a investigação do almirantado e o que se saberia em Dunedin sobre aquele culto nefasto? E o mais surpreendente de tudo: que profunda e sobrenatural ligação de datas era essa que dava um significado maligno e agora inegável aos vários episódios tão cuidadosamente anotados por meu tio?

A 1° de março (nosso 28 de fevereiro, segundo a hora do meridiano de Greenwich) haviam ocorrido o terremoto e a tempestade. De Dunedin o Alert e sua revoltante tripulação haviam zarpado ansiosamente, como se atendessem a um imperioso chamado, enquanto do outro lado da terra poetas e artistas haviam começado a sonhar com uma estranha e lodosa cidade ciclópica, e um jovem escultor moldara durante o sono a forma do temível Cthulhu. A 23 de março a tripulação da Emma desembarcava numa ilha desconhecida, deixando ali seis mortos; e na mesma data os sonhos de homens sensíveis assumiam grande nitidez e se ensombreciam com o pavor da perseguição maligna de um monstro gigantesco, ao passo que um arquiteto enlouquecia e um escultor mergulhava repentinamente em total delírio! E o que dizer daquela tempestade de 2 de abril – data em que cessaram todos os sonhos da cidade lodosa e Wilcox emergiu incólume do cativeiro de sua estranha febre? O que dizer de tudo isso e das alusões do velho Castro sobre os Antigos, submersos filhos das estrelas cujo reinado estava próximo, do fervoroso culto que lhes era dedicado e do domínio que tenham sobre os sonhos? Estaria eu cambaleando à beira de horrores cósmicos além da capacidade humana de suportá-los? Se assim fosse, deveriam ser horrores apenas da mente, pois de alguma forma o dia 2 de abril pusera fim a qualquer ameaça monstruosa que iniciara seu assédio contra a alma da humanidade.

Naquela noite, após um dia inteiro de telegramas apressados e tomada de providências, despedi-me do meu anfitrião e embarquei num trem para São Francisco. Em menos de um mês estava em Dunedin, onde, contudo, descobri que pouco se sabia acerca dos estranhos membros do culto que haviam freqüentado as velhas tavernas do cais. A ralé do porto era comum demais para fazer jus a qualquer menção especial, embora se falasse vagamente sobre uma excursão terra adentro que aqueles mestiços haviam feito, e durante a qual tênues batidas de tambor e labaredas vermelhas nas colinas distantes tinham-se feito notar.

Em Auckland soube que Johansen havia retornado com os cabelos loiros totalmente brancos após um interrogatório superficial e inconcludente em Sydney, e que depois vendera sua pequena casa na Rua Oeste e zarpara com a esposa para seu antigo lar em Oslo. Nem aos seus amigos quis contar sobre a sua eletrizante experiência mais do que contara aos oficiais do almirantado, e o máximo que puderam fazer foi dar-me o endereço dele em Oslo.

Depois disso fui a Sydney e conversei sem proveito algum com marinheiros e integrantes do tribunal marítimo. Vi o Alert, agora vendido e sendo usado como cargueiro no Cais Circular, em Sydney Cove, mas nada ganhei com a visita à neutra embarcação. A imagem agachada, com sua cabeça de polvo, corpo de dragão, asas escamosas e pedestal coberto de hieróglifos era conservada no Museu de Hyde Park, e eu a estudei detidamente, constatando ser obra de rematada e artística malignidade, dotada do mesmo mistério profundo, assustadora antigüidade e estranheza alienígena de material que eu observara no espécime menor de Legrasse. O curador me contou que os geólogos consideravam-na um monstruoso enigma, pois juravam não haver no mundo rocha igual àquela. Então me lembrei, com um calafrio, do que o velho Castro dissera a Legrasse sobre os primordiais Grandes: “Tinham vindo das estrelas, trazendo consigo Suas imagens”.

Abalado por uma revolução mental como nunca experimentara antes, resolvi visitar o imediato Johansen em Oslo. Embarcando rumo a Londres, mal cheguei lá e tomei imediatamente um navio para a capital norueguesa, onde desembarquei em um dia de outono nos bem cuidados cais à sombra do Egeberg.

O endereço de Johansen, segundo apurei, ficava na Cidade Velha do rei Harold Haardrada, o bairro que manteve vivo o nome de Oslo durante os séculos em que a capital mascarou-se sob o nome de “Cristiânia”. Fiz o breve trajeto de táxi, e foi com o coração palpitante que bati à porta de um antigo e belo edifício com fachada de estuque. Atendeu-me uma mulher de rosto triste vestida de preto, e a decepção se abateu sobre mim quando ela me informou, num inglês trôpego, que Gustaf Johansen havia morrido.

Ele não sobrevivera muito tempo após o seu regresso, contou-me sua viúva, pois os acontecimentos no mar em 1925 haviam-no al quebrado. Johansen não contara à esposa mais do que contara ao público, porém deixara um longo manuscrito – sobre “assuntos técnicos”, segundo disse – escrito em inglês, com o propósito evidente de salvaguardá-la do perigo de uma leitura casual. Durante um passeio por uma vi ela estreita próxima às docas de Gothenburg, fora derrubado por um pesado fardo de jornais caído da janela de um sótão. Dois marinheiros de Lascar imediatamente ajudaram-no a levantar-se, mas antes que a ambulância chegasse, ele já estava morto. Os médicos não encontraram causa específica para o óbito, atribuindo-o a problemas cardíacos e constituição debilitada.

Senti então remoer-me as entranhas aquele obscuro terror que nunca mais me deixará até que eu também venha a repousar, “acidentalmente” ou de outra forma. Tendo persuadido a viúva de que minha ligação com os “assuntos técnicos” de seu marido davam-me direito ao manuscrito, levei o documento comigo e comecei a lê-lo no navio de volta a Londres.

A redação era simples e sem elegância de estilo – tentativa de marinheiro ingênuo de compor um diário a posterióri – e procurava reconstituir, dia a dia, aquela última e fatídica viagem. Não há por que transcrevê-lo na íntegra com toda a sua ilegibilidade e redundâncias, mas narrarei o essencial do seu conteúdo para mostrar por que o barulho da água contra o casco do navio tornou-se tão insuportável para mim que tampei meus ouvidos com algodão.

Johansen, graças a Deus, não sabia de tudo, mesmo tendo visto a cidade e a Coisa, mas nunca voltarei a dormir calmamente de novo ao pensar nos horrores que espreitam incessantemente a vida no tempo e no espaço, e naquelas ímpias blasfêmias oriundas de imemoriais estrelas que sonham nas profundezas do mar, conhecidas e adoradas por um culto de pesadelo pronto e ansioso por soltá-las sobre o mundo assim que outro terremoto traga de novo à tona sua monstruosa cidade de pedra.

A viagem de Johansen havia começado exatamente como ele contou ao almirantado. A escuna Emma, com lastro, deixara Auckland a 20 de fevereiro, e sentira toda a força da tempestade causada pelo terremoto que deve ter feito emergir os horrores que preencheram os sonhos de tantos homens. Recuperado o controle da embarcação, esta prosseguia normalmente quando foi abordada pelo Alert a 22 de março, e pude sentir a tristeza do imediato ao descrever o bombardeio e afundamento do seu barco. Dos satanistas trigueiros do Alert ele fala com significativo horror. Havia neles algo de peculiarmente abominável que fazia com que a sua destruição parecesse quase um dever, e Johansen demonstra ingênua surpresa frente à acusação de desumanidade levantada contra o seu grupo durante os trabalhos da corte de inquérito. Então, levados adiante pela curiosidade no iate capturado, sob o comando de Johansen, os homens avistaram uma enorme coluna de pedra que se projetava fora do mar, e na latitude sul 47° 9′ e longitude oeste 126° 43′, deram com um litoral de lama, lodo e alvenaria ciclópica coberta de musgo que não podia ser outra coisa senão a substância tangível do supremo terror do planeta – a cadavérica cidade-pesadelo de R’lyeh, construída há incontáveis eras antes da História pelos gigantescos e nefastos vultos procedentes das estrelas sem luz. Ali jaziam o grande Cthulhu e suas hordas, ocultos em verdes criptas lodosas de onde finalmente, após ciclos incalculáveis, emitiam os pensamentos que infundem medo nos sonhos dos sensíveis e conclamam imperiosamente os fiéis a uma peregrinação de libertação e restauração. Johansen nada suspeitava sobre isso, mas Deus sabe que ele logo veria o bastante!

Suponho que apenas o cume de uma montanha, a revoltante cidadela coroada por um monólito, onde estava sepultado o grande Cthulhu, emergiu verdadeiramente das águas. Quando penso na extensão de tudo o que pode estar à espreita lá embaixo, quase tenho vontade de me matar de uma vez. Johansen e seus homens estavam boquiabertos perante a cósmica majestade daquela gotejante Babilônia de demônios ancestrais, e devem ter adivinhado, sem maior orientação, que não se tratava de nada proveniente deste ou de qualquer planeta são. Perplexo temor diante do incrível tamanho dos blocos de pedra esverdeados, da estonteante altura do grande monólito esculpido e da assombrosa identidade entre as colossais estátuas e baixos-relevos e a esdrúxula imagem encontrada no relicário do Alert, é flagrante em cada linha da assustada descrição do imediato.

Sem ter qualquer noção da escola artística a que se dá o nome de futurismo, Johansen chegou a algo muito próximo quando falou sobre a cidade; pois, ao invés de descrever qualquer estrutura ou edifício definidos, ele se refere apenas às amplas impressões de vastos ângulos e superfícies de pedra superfícies grandes demais para pertencer a qualquer coisa correta ou apropriada nesta terra, e ímpias com aquelas horríveis imagens e hieróglifos. Menciono a alusão dele a ângulos porque sugere algo que Wilcox me dissera sobre seus arrepiantes sonhos; ele havia dito que a geometria do local do sonho era anormal, não-euclidiana, e perturbadoramente repleta de esferas e dimensões alheias às nossas. Agora um marujo iletrado sentia a mesma coisa encarando a terrível realidade.

Johansen e seus homens desembarcaram numa lamacenta encosta daquela monstruosa acrópole, e galgaram com dificuldade os titânicos blocos escorregadios que não poderiam ser uma escada para mortais. No céu, o próprio sol parecia distorcido quando visto através do miasma polarizador que subia daquela perversão encharcada de mar, e uma serpenteante ameaça e suspense pareciam espreitar de soslaio naqueles insanamente ilusórios ângulos de rocha talhada, onde um segundo olhar mostrava concavidade após o primeiro ter mostrado convexidade.

Algo muito próximo ao pavor já sobreviera a todos os exploradores antes que coisa mais definida do que pedra, lodo e algas fosse vista. Cada um deles teria fugido se não temesse a zombaria dos demais, e foi com entusiasmo mínimo que procuraram – em vão, como se veria – alguma pequena lembrança para levar consigo.

Foi Rodrigues, o português, que galgou o pé do monólito e gritou o que havia encontrado. Os demais seguiram-no e olharam cheios de curiosidade a imensa porta esculpida com o já familiar baixo relevo da lula-dragão. Segundo Johansen, era como uma enorme porta de celeiro; e todos julgaram ser uma porta devido ao dintel, umbral e batente ornamentados em volta, embora não conseguissem determinar se era plana como um alçapão ou oblíqua como uma porta externa de porão. Como Wilcox diria, a geometria daquele lugar era toda errada. Não se podia ter certeza de que o mar e a terra fossem horizontais, daí a posição relativa de tudo o mais parecer fantasmagoricamente variável.

Briden empurrou a pedra em diversos lugares, sem resultado. Em seguida Donovan tateou delicadamente as beiradas, pressionando cada ponto em separado. Escalou interminavelmente a grotesca cornija de pedra – isto é, diríamos “escalar” se a coisa não fosse mesmo horizontal – enquanto os homens se perguntavam, atônitos, corno alguma porta no universo poderia ser tão vasta. Então, muito devagar e suavemente, o painel de meio hectare de extensão pôs-se a ceder para dentro na parte de cima, ao que puderam constatar que estava equilibrada.

Donovan deslizou ou de alguma forma propulsou-se para baixo ou ao longo do batente e veio juntar-se aos companheiros, e todos assistiram à estranha recessão do portal monstruosamente esculpido. Naquela fantasia de distorção prismática, ele se movia anomalamente em sentido diagonal, subvertendo todas as regras da matéria e da perspectiva.

  A abertura era negra, de uma escuridão quase palpável. Aquela tenebrosidade tinha, com efeito, uma qualidade positiva, pois escurecia partes das paredes internas que deveriam estar claras, e na verdade se evolava como fumaça de seu imemorial aprisionamento, visivelmente eclipsando o sol à medida em que se esquivava pelo céu encolhido e convexo com esvoaçantes asas membranosas. O fedor que subiu das recém-abertas profundezas era insuportável, e logo depois Hawkins, que tinha ouvido apurado, julgou captar um asqueroso chapinhar vindo lá de baixo. Todos ficaram atentos, e continuavam atentos quando Aquilo assomou babosamente à vista e, às apalpadelas, espremeu Sua gelatinosa imensidão verde através da passagem negra para fora, ganhando o ar contaminado daquela peçonhenta cidade de loucura.

A caligrafia do pobre Johansen quase cedeu ao escrever essa parte. Dos seis homens que não voltaram ao navio, ele acha que dois morreram de puro pavor naquele instante amaldiçoado. A Coisa não pode ser descrita – não existem palavras capazes de expressar tais abismos de loucura estridente e imemorial, tais contradições alienígenas de toda matéria, força e harmonia cósmica. Uma montanha caminhava, ou cambaleava! Deus! Não admira que do outro lado da terra um grande arquiteto enlouquecesse e o pobre Wilcox delirasse de febre naquele instante telepático! A Criatura dos ídolos, o verde e pegajoso rebento das estrelas, despertara para reclamar o que era seu. As estrelas estavam novamente alinhadas, e o que um culto milenar falhara em fazer por fé, um bando de marinheiros inocentes fizera por acaso. Após trilhões de anos, o grande Cthulhu estava solto mais uma vez, e ávido de prazer.

Três homens foram varridos pelas flácidas garras antes que alguém pudesse se voltar para fugir. Que descansem em paz, se é que há algum descanso no universo. Foram eles Donovan, Guerrera e Angstrom. Parker escorregou enquanto os outros três disparavam freneticamente sobre panoramas intermináveis de rocha esverdeada rumo ao bote, e Johansen jura que ele foi tragado por um ângulo de alvenaria que não devia estar lá, um ângulo que, sendo agudo, comportava-se como se fosse obtuso. De modo que somente Briden e Johansen alcançaram o bote, e remaram desesperadamente para o Alert enquanto a montanhosa monstruosidade descia desajeitadamente pelas pedras limosas e hesitava, cambaleante, à beira d’água.

O vapor continuava a sair do iate a despeito da saída de todos os homens para a praia, portanto bastou alguns momentos de febril corre-corre entre rodas e motores para fazer o Alert partir. Lentamente, em meio aos horrores distorcidos daquele indescritível e infernal cenário, o iate começou a singrar as águas mortíferas, enquanto sobre as pedras lavradas daquela praia sepulcral que não pertencia a este planeta, a Coisa titânica vinda das estrelas espumava e vozeava como Polifemo praguejando contra o navio de Odisseu em fuga. Então, mais ousado que o lendário ciclope, o grande Cthulhu deslizou oleosamente para dentro d’água e começou a perseguir o iate, erguendo ondas com suas braçadas de potência cósmica. Briden olhou para trás e enlouqueceu, com ocasionais acessos de riso, até que a morte foi encontrá-lo certa noite na cabina, enquanto Johansen errava pelo convés a delirar.

Mas Johansen ainda não se rendera. Sabendo que a Coisa alcançaria facilmente o Alert antes que o vapor atingisse a pressão máxima, optou por uma saída desesperada: regulando o motor para velocidade total, correu como um raio ao convés e reverteu o timão. O mar cobriu-se de remoinhos e espuma, e enquanto o vapor subia cada vez mais, o valente norueguês dirigiu a nave contra a abominação gelatinosa que o perseguia erguendo-se das imundas ondas espumantes como o castelo de popa de um galeão demoníaco. A medonha cabeça de polvo com tentáculos retorcendo-se chegava quase à altura do gurupés do resoluto iate, mas Johansen prosseguiu inabalavelmente.

Houve um estouro como o de uma bexiga rebentando, o derrame de uma nojeira lamacenta como a que jorra de um peixe-lua partido, um fedor como de mil sepulturas abrindo-se de chofre e um som que o cronista negou-se a registrar. Por um instante o barco foi emporcalhado por uma nuvem verde, acre e cegante, e logo depois havia apenas um empeçonhado fervilhar à ré, onde – Deus do Céu! a espalhada plasticidade daquele inominável rebento sideral estava nebulosamente recompondo-se na sua execrável forma original, distanciando-se cada vez mais à medida em que o Alert ganhava velocidade de seu vapor ascendente.

Isso foi tudo. Depois disso Johansen limitou-se a contemplar o ídolo na cabina e a providenciar comida para si e para o maníaco risonho do seu lado. Não tentou navegar depois daquela façanha, pois a experiência como que lhe esvaziara a alma. Sobreveio então a tempestade de 2 de abril e uma concentração de nuvens que lhe obscureceram a consciência. Teve uma sensação de turbilhão espectral por líquidos golfos de infinito, de Jornadas estupefacientes através de universos giratórios numa cauda de cometa, e de mergulhos histéricos das profundezas do inferno até a lua e da lua de volta às profundezas do inferno, tudo isso animado por um coro gargalhante dos deuses ancestrais, disformes e hilários, e dos zombeteiros demônios do Tártaro, verdes e com asas de morcego.

Saído desse sonho veio o socorro – o Vigilant, a corte do almirantado, as ruas de Dunedin e a longa viagem de volta ao lar, à velha casa às margens do Egeberg. Não podia falar nada – tê-lo-iam julgado louco. Ele haveria de escrever o que sabia antes que a morte chegasse, mas era necessário que sua esposa de nada desconfiasse. A morte viria como uma bênção se ao menos obliterasse as lembranças.

Esse foi o documento que eu li, e que então coloquei na caixa de metal junto com o baixo-relevo e os papéis do professor Angell. A eles acrescentarei este meu relato -prova da minha sanidade, no qual reuni as peças de algo que, espero, nunca mais ninguém volte a decifrar. Vi tudo o que o universo pode conter de horror, e depois disso até mesmo os céus primaveris e as flores de verão serão veneno para mim. Mas não creio que minha vida será longa. Como meu tio se foi, como o pobre Johansen se foi, também eu irei. Sei demais, e o culto ainda vive.

Cthulhu também vive ainda, acredito, naquele precipício de pedra que o vem abrigando desde a infância do sol. Sua amaldiçoada cidade tornou a afundar, pois o Vigilant percorreu aquela região após a tempestade de abril; mas seus adoradores na terra ainda urram, saltam e matam ao redor de ídolos sobre monólitos em locais ermos e solitários.

Ele deve ter sido surpreendido pelo afundamento quando se achava no seu abismo negro, do contrário o mundo inteiro estaria agora berrando de pavor e frenesi. Quem sabe qual será o final? O que emergiu pode afundar, e o que afundou pode emergir. A repugnância suprema aguarda sonhando nas profundezas e a podridão paira sobre as precárias cidades dos homens. O tempo virá… mas não devo, nem posso pensar! Só me resta a esperança de que, se eu não sobreviver a este manuscrito, meus testamenteiros tenham mais precaução que audácia e impeçam que outros olhos o vejam.</p>
            <Link className="links" to="Dagon">
            Dagon {' '}
            </Link>
            <Link className="links" to='Azathoth'>
            Azathoth
            </Link>
          </div>
            )
    }
}
export default Cthulu;