import React, { Component } from "react";
import { Link } from "react-router-dom";
import cthulu from "../images/cthulu.jpg"
import "./index.css";
class Dagon extends Component{
    render(){
        return(
            <div id= "body">
               <img src={cthulu} className="logo" alt="logo" />
                <p id= "text">Estou escrevendo isto sob uma grande tensão mental, já que nesta noite eu não deverei mais existir.
                     Sem um centavo, e no fim do meu suprimento de remédio que por si só consegue tornar minha vida tolerável, 
                     eu já não consigo suportar mais a tortura; e devo me atirar dessa janela do sótão em direção a rua esquálida lá embaixo.
                      Não pense que por causa da minha escravidão à morfina eu seja um fraco ou um degenerado. Quando você tiver lido estas páginas rabiscadas às pressas você poderá imaginar, porém nunca perceber completamente, o motivo pelo qual eu preciso ter o completo esquecimento ou a morte.

Foi num dos trechos mais abertos e pouco frequentados do extenso Pacífico, que o paquete do qual eu era comissário de bordo foi vítima de um navio corsário alemão. A grande guerra estava até então bem no seu início, e as forças oceânicas dos Hunos² não haviam afundado completamente para as suas degradações posteriores; de modo que nossa embarcação se tornara um legítimo prêmio, enquanto nós da tripulação fomos tratados com toda a equidade e consideração devida a nós como prisioneiros navais. Era tão liberal, de fato, a disciplina dos nossos captores, que cinco dias após termos sido tomados, eu consegui escapar sozinho num pequeno barco com água e suprimentos para um bom período de tempo.

Quando finalmente me encontrei à deriva e livre, eu não tinha a mínima ideia do que me rodeava. Nunca um navegador competente, eu só podia adivinhar vagamente pelo sol e pelas estrelas que eu estava um pouco ao sul do Equador. Da longitude eu nada sabia, e nenhuma ilha ou linha costeira estava à vista. O tempo se manteve firme, e por incontáveis dias eu flutuei sem direção debaixo do sol escaldante; esperando ou por algum navio passageiro, ou ser atirado às praias de alguma terra habitável. Mas nem navio ou terra apareceu, e eu comecei a me desesperar em minha solidão sobre a vastidão ondulante de interminável azul.

A mudança aconteceu enquanto eu dormia. Seus detalhes eu jamais saberei; já o meu sono, apesar de perturbado e infestado de sonhos, era contínuo. Quando finalmente acordei, foi para me encontrar sugado pela metade numa extensão viscosa de lama negra infernal, que se estendia em monótonas ondulações até onde minha vista alcançava, e na qual meu barco estava enterrado com certa distancia.

Embora alguém pudesse muito bem imaginar que a minha primeira sensação seria de surpresa com uma transformação tão prodigiosa e inesperada de cenário, eu estava na realidade mais horrorizado do que surpreso; pois havia no ar e no solo apodrecido uma característica sinistra que me gelou até o âmago. A região estava pútrida com as carcaças de peixes em decomposição, e de outras coisas menos descritíveis que eu vi protuberando da desagradável lama da planície sem fim. Talvez eu não devesse esperar transmitir em meras palavras o horror inexprimível que pode habitar num silêncio absoluto e na imensidão estéril. Não existia nada ao alcance do ouvido, e nada a vista salvo uma vasta extensão de lodo preto; contudo a própria plenitude da quietude e a homogeneidade da paisagem me oprimiram com um medo nauseante.

O sol estava brilhando de um céu que me parecia quase preto em sua crueldade sem nuvens; como se refletisse o pântano manchado sob os meus pés. Enquanto eu me rastejava em direção ao barco encalhado, eu percebi que apenas uma teoria poderia explicar minha situação. Através de alguma de uma convulsão vulcânica sem precedentes, uma parte do fundo do oceano devia ter sido jogada para a superfície, expondo regiões que durante inúmeros milhões de anos haviam ficado escondidas sob profundezas aquáticas insondáveis. Tão grande era a extensão da nova terra que se elevara abaixo de mim, que eu não pude detectar o mais tênue ruído do oceano, por mais que forçasse os ouvidos. Também não havia qualquer ave marinha para devorar as coisas mortas.

Durante muitas horas eu fiquei sentado pensando e remoendo no barco, que estava caído de lado e proporcionando um pouco de sombra à medida que o sol se movia pelos céus. No decorrer do dia o chão perdeu um pouco da sua viscosidade, e pareceu que provavelmente, num curto espaço de tempo, se tornaria seco o suficiente para o propósito de viajar. Naquela noite eu dormi, mas pouco, e no dia seguinte fiz para mim mesmo um pacote contendo comida e água, preparações para uma jornada terrestre em busca do mar desaparecido e de um possível resgate.

Na terceira manhã eu achei o solo seco o suficiente para caminhar sobre ele com facilidade. O odor dos peixes era enlouquecedor; mas eu estava preocupado demais com coisas mais graves para me importar com um mal tão leve, e parti corajosamente rumo a um objetivo desconhecido. Durante todo o dia eu caminhava firmemente na direção oeste, guiado por um outeiro distante que se elevara mais alto que qualquer outra elevação no deserto ondulado. Naquela noite eu acampei, e no dia seguinte ainda viajei em direção ao outeiro, embora aquele objeto parecesse estar pouca coisa mais perto do que da primeira vez em que eu o espiei. Pela quarta noite eu atingi a base do monte, que acabou sendo muito mais alto do que parecera à distância; um vale interposto destacava seu perfil da superfície geral. Exausto demais para subir, eu dormi na sombra da colina.

Não entendo por que meus sonhos foram tão agitados naquela noite; mas antes da curva fantasticamente acentuada da lua minguante ter-se erguido muito acima do lado oriental da planície, eu fui acordado num suor frio, determinado a não dormir novamente. Tais visões as quais eu havia experienciado eram demais para suportar novamente. E sob o brilho do luar eu percebi o quão imprudente eu havia sido por viajar durando o dia. Sem o brilho do sol abrasador, minha jornada teria me custado menos energia; na verdade, eu agora me sentia bastante capaz para realizar a subida que me havia intimidado ao entardecer. Apanhando minhas provisões, eu parti para a crista da elevação.

Eu já disse que a monotonia constante da planície ondulada era uma fonte de horror vago para mim, mas acho que meu horror foi maior quando alcancei o cume do monte e olhei para o outro lado, para um imensurável fosso ou desfiladeiro, cujos recessos negros a lua ainda não havia se erguido o suficiente para iluminar. Eu me senti no limiar do mundo, olhando sobre sobre a borda para um caos insondável de noite eterna. Pelo meu terror passaram curiosas reminiscências do Paraíso Perdido³, e da hedionda ascensão de Satã pelos reinos indecorosos das trevas.

À medida que a Lua subiu mais alto no céu, eu comecei a notar que as encostas do vale não eram tão perpendiculares quanto eu havia imaginado. Ressaltos e afloramentos da rocha forneciam apoios razoavelmente fáceis de pés para uma descida, enquanto após um mergulho de algumas centenas de pés, o declive se tornou bastante gradual. Impelido por um impulso que não consigo definitivamente analisar, desci com dificuldade pelas rochas e parei na encosta menos íngreme abaixo, fitando as profundezas tenebrosas onde nenhuma luz havia jamais penetrado.

De repente minha atenção foi capturada por um vasto e singular objeto na encosta oposta, que se erguia abruptamente a cerca de cem jardas à minha frente; um objeto que brilhou esbranquiçadamente sob os recentes raios agraciados da Lua crescente. Que isso fosse meramente um pedaço gigantesco de rocha, eu logo me assegurara; mas eu estava consciente de uma distinta impressão de que seu contorno e posição não eram de todo o trabalho da Natureza. Um exame mais minucioso me encheu de sensações que não consigo expressar; pois apesar de sua enorme magnitude, e sua posição num abismo que ficara escondido no fundo do mar desde que o mundo era jovem, eu percebi sem sombra de dúvidas que o estranho objeto era um monólito bem moldado cujo volume maciço havia conhecido o artesanato e talvez a adoração de criaturas vivas e pensantes.

Pasmo e assustado, mas não sem uma certa excitação de um prazer científico ou arqueológico, eu examinei meu entorno mais de perto. A Lua, agora perto do zênite, brilhava estranhamente e vividamente acima das escarpas altas que cercavam o abismo, revelando o fato de que um um extenso corpo d’água corria em seu fundo, até se perder de vista em ambas as direções, e quase lambia meus pés enquanto eu estava na encosta. Do outro lado do abismo, as pequenas ondas lavavam a base do monólito ciclópico; sobre cuja superfície eu podia agora distinguir tanto inscrições quanto esculturas brutas. A escrita estava num sistema de hieróglifos desconhecido para mim, e diferente de tudo que eu já vira em livros; consistindo em sua maior parte de símbolos aquáticos convencionalizados como peixes, enguias, polvos, crustáceos, moluscos, baleias, e coisas assim. Diversos caracteres obviamente representavam coisas marinhas que eram desconhecidas para o mundo moderno, mas cujas formas em decomposição eu havia observado na planície erguida do oceano.
Foram os entalhes pictóricos, porém, que mais me encantaram. Claramente visível através da água interveniente por conta do seu tamanho, havia um arranjo de baixos-relevos cuja temática teria provocado a inveja de Doré⁴. Imagino que aquelas coisas deviam supostamente ilustrar homens – ao menos, um certo tipo de homens; embora as criaturas fossem mostradas divertindo-se como peixes nas águas de alguma gruta marinha, ou venerando algum santuário em forma de monólito que também parecera estar submerso. De seus rostos e formas eu não ouso falar com detalhes; sua mera recordação me deixa aturdido. Grotesco além da imaginação de um Poe⁵ ou de um Bulwer⁶, eles eram abominavelmente humanos em seu contorno geral, apesar das mãos e pés palmados, dos lábios chocantemente largos e flácidos, dos olhos saltados e vítreos, e outras feições ainda menos agradáveis de se lembrar. Curiosamente, eles pareciam ter sido cinzelados muito fora de proporção em relação ao cenário de fundo; pois uma das criaturas era mostrada no ato de matar uma baleia, representada com um tamanho pouco maior do que o seu. Eu comentei, como digo, sobre seu jeito grotesco e estranho tamanho; mas num momento achei que eram apenas os deuses imaginários de alguns pescadores primitivos ou tribos marítimas; alguma tribo cujos derradeiros descendentes teriam perecido muitas eras antes do primeiro ancestral do Homem de Piltdown⁷ ou do Neandertal ter nascido. Extasiado diante daquele inesperado vislumbre de um passado além da concepção do mais ousado antropólogo, eu fiquei ali meditando enquanto a Lua lançava curiosos reflexos no silencioso canal à minha frente.

Então de repente eu a vi. Com apenas uma leve agitação para indicar sua subida à superfície, a coisa emergiu para fora das águas escuras. Enorme, polifêmica e repugnante, ela disparou como um monstro estupendo do pesadelo para o monólito, sobre o qual jogou seus gigantescos braços escamosos, enquanto inclinava a cabeça horripilante produzindo sons ritmados. Pensei ter enlouquecido então.

De minha subida frenética da encosta e do penhasco, e da minha delirante jornada de volta ao barco encalhado, pouco me recordo. Creio que cantei muito, e ri estranhamente quando era incapaz de cantar. Eu tenho vagas recordações de uma grande tempestade algum tempo depois de alcançar o barco; de qualquer forma, sei que ouvi o estrondo de trovões e outros ruídos que a natureza expressa somente em seus humores mais selvagens.

Quando saí das trevas eu estava num hospital em São Francis­co; levado pelo capitão de um navio americano que recolhera meu barco no meio do oceano. Em meu delírio eu falei muito, mas descobri que minas palavras receberam pouca atenção. Sobre qualquer afloramento de terra no meio do Pacífico, meus salvadores não sabiam nada a respeito; nem eu julguei necessário insistir em algo de que sabia que eles não poderiam acreditar. Procurei certa vez um famoso etnólogo, e o diverti com perguntas curiosas sobre a antiga lenda filistina de Dagon, o Deus-Peixe; mas logo percebendo que ele era um racionalista irremediável, eu não pressionei meus inquéritos.

É durante a noite, especialmente quando a lua está muito curva e minguante, que eu vejo a coisa. Tentei a morfina; mas a droga me deu apenas um alívio temporário, e me arrastou para suas garras como um escravo sem esperança. Então agora eu pretendo acabar com tudo, tendo escrito um relato completo para a informação ou a desdenhosa diversão de meus semelhantes. Muitas vezes me pergunto se tudo não teria passado de pura fantasmagoria — uma simples fantasia febril enquanto eu jazia, castigado pelo sol e delirante naquele barco sem cobertura, depois da minha fuga do navio de guerra alemão. Isso eu me pergunto, mas sempre me vem uma visão terrivelmente pavorosa em resposta. Não consigo pensar no mar profundo sem estremecer com as coisas inomináveis que podem neste exato momento estar arrastando-se e espojando-se em seu leito viscoso, adorando seus antigos ídolos de pedra e cinzelando a sua própria e detestável semelhança em obeliscos submarinos de granito encharcado. Eu sonho com o dia em que elas poderão ascender acima dos vagalhões para arrastar para o fundo com suas garras fétidas, os remanescentes de uma humanidade debilitada, exaurida pela guerra — o dia em que a terra deva afundar, e o fundo negro do oceano erguer-se em meio a um pandemônio universal.

O fim está próximo. Ouço um ruído à porta, como se um imenso corpo escorregadio a estivesse serrando. Ele não deve me encontrar. Deus, aquela mão! A janela! A janela!</p>

            <Link className="links" to="History">
            History {' '}
            </Link>
            <Link className="links" to='Dashboard'>
            Dashboard
            </Link>
          </div>
            )
    }
}
export default Dagon;